// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb_6ASjC9ug5lnvSOXf7-oWjxusxcZ2UA',
    appId: '1:903270724046:web:27a2044c3239bbbb6fbb9f',
    messagingSenderId: '903270724046',
    projectId: 'djcsi-library',
    authDomain: 'djcsi-library.firebaseapp.com',
    storageBucket: 'djcsi-library.appspot.com',
    measurementId: 'G-PT8QKZ9HYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVYyohlL6i8DDyAdv43AQouquzwTyNFQ8',
    appId: '1:903270724046:android:70fed0e393ed54be6fbb9f',
    messagingSenderId: '903270724046',
    projectId: 'djcsi-library',
    storageBucket: 'djcsi-library.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvOWHoDMqqU33HzqVESr8mjZagA5AgqI4',
    appId: '1:903270724046:ios:3ba0cbcadbe820616fbb9f',
    messagingSenderId: '903270724046',
    projectId: 'djcsi-library',
    storageBucket: 'djcsi-library.appspot.com',
    iosClientId: '903270724046-ru2cma0as1bj1kksj07tk2sfgjnmk5jr.apps.googleusercontent.com',
    iosBundleId: 'com.example.csiLibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvOWHoDMqqU33HzqVESr8mjZagA5AgqI4',
    appId: '1:903270724046:ios:44e51e19e0cf62fd6fbb9f',
    messagingSenderId: '903270724046',
    projectId: 'djcsi-library',
    storageBucket: 'djcsi-library.appspot.com',
    iosClientId: '903270724046-60cd8vr569a19gau9emd05v3thpud28a.apps.googleusercontent.com',
    iosBundleId: 'com.example.csiLibrary.RunnerTests',
  );
}
